// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var $$Promise = require("reason-promise/src/js/promise.js");

function getA(param) {
  return $$Promise.resolved(12);
}

function getB(a) {
  return $$Promise.resolved(a + 12 | 0);
}

function getC(b) {
  return $$Promise.resolved(b + 12 | 0);
}

var Promise_ = {
  let_: $$Promise.flatMap
};

var PromiseMap = {
  let_: $$Promise.map
};

$$Promise.get($$Promise.flatMap($$Promise.flatMap($$Promise.resolved(12), (function (a) {
                return $$Promise.resolved(a + 12 | 0);
              })), (function (b) {
            return $$Promise.resolved(b + 12 | 0);
          })), (function (res) {
        console.log(res);
        
      }));

var Zero = {};

$$Promise.get($$Promise.flatMap($$Promise.flatMap($$Promise.resolved(12), (function (a) {
                return $$Promise.resolved(a + 12 | 0);
              })), (function (b) {
            return $$Promise.resolved(b + 12 | 0);
          })), (function (res) {
        console.log(res);
        
      }));

var First = {};

var result = $$Promise.flatMap($$Promise.resolved(12), (function (a) {
        return $$Promise.flatMap($$Promise.resolved(a + 12 | 0), (function (b) {
                      return $$Promise.map($$Promise.resolved(b + 12 | 0), (function (c) {
                                    return c;
                                  }));
                    }));
      }));

var Second = {
  result: result
};

exports.getA = getA;
exports.getB = getB;
exports.getC = getC;
exports.Promise_ = Promise_;
exports.PromiseMap = PromiseMap;
exports.Zero = Zero;
exports.First = First;
exports.Second = Second;
/*  Not a pure module */
